# Generated by Django 5.2.13 on 2026-04-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='km_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
