# Generated by Django 5.2.13 on 2026-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicleimage_options_vehicleimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
