# Generated by Django 5.2.13 on 2026-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicleimage_image_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='market_value_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='market_value_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='market_value_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='document_stage',
            field=models.CharField(choices=[('general', 'General'), ('purchase', 'Purchase'), ('sale', 'Sale')], default='general', max_length=20),
        ),
    ]
