# Generated by Django 5.2.13 on 2026-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='labour',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='service',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='2025-01-01', max_length=50),
            preserve_default=False,
        ),
    ]
