# Generated by Django 5.2.13 on 2026-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_labour_expense_amount_remove_expense_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller_aadhaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_aadhaar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
